env:
  browser: true
  es6: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  import/extensions: 0
